// SPDX-License-Identifier: MIT OR Apache-2.0
//! Kimi Code (Moonshot AI) agent state.
//!
//! Layout (verified locally against a live ~/.kimi-code, 34/34
//! workspaces matched):
//! - workspaces.json — map of bucket -> {root, name, ...}; the bucket
//!   key and the root value both ride the rewrite (the key is a
//!   derived token, the root an identity field)
//! - session_index.jsonl — per session: sessionDir (absolute, contains
//!   the bucket segment) + workDir
//! - sessions/<bucket>/session_<uuid>/{state.json,agents/main/wire.jsonl,
//!   agents/main/tasks/*.json} — workDir / homedir / cwd identity fields
//! - sessions/.index-cache/scan.json — a regenerable scan cache holding
//!   BARE bucket ids in non-identity fields ("ws"); rewritten as text
//!   so the derived bucket token moves
//! - file-history/<bucket> and workspace-trust/<bucket> — FILES named
//!   by the bucket (workspace-trust holds {"root": ...}; file-history
//!   only session ids)
//! - server/events/ — the background server's event stream:
//!   event.workspace.updated carries payload.workspace.{id,root} and
//!   session events carry payload.session.{workspace_id,metadata.cwd};
//!   these are the identity layer the server replays state from
//!   (server/instances holds only pid/port runtime records)
//! - bucket = wd_<basename(root)>_<sha256(root)[:12]> — basename
//!   verbatim (underscores and dashes both occur in the wild), only
//!   the hash disambiguates same-named roots
//!
//! search-index/ is an LMDB binary cache (CURRENT + db.lock + WAL):
//! never rewritten (binary), regenerated by the agent itself.
//! cache/, logs/, telemetry/ and updates/ are covered by the shared
//! SKIP_DIRS and stay untouched.

use super::{mk, Adapter, Finding};
use crate::backup::Backup;
use crate::ctx::Ctx;
use crate::encodings;
use crate::rewriters;
use crate::spec::ReplaceSpec;
use anyhow::Result;
use std::path::PathBuf;

/// state subtrees that carry project references; enumerating them keeps
/// the binary search-index and the server runtime out of the walk
const SUBTREES: &[&str] = &[
    "sessions",
    "file-history",
    "workspace-trust",
    "user-history",
    "server",
    "plugins",
    "skills",
];

/// top-level state files that carry project references
const TOP_FILES: &[&str] = &[
    "workspaces.json",
    "session_index.jsonl",
    "config.toml",
    "mcp.json",
    "tui.toml",
];

pub struct KimiCodeAdapter;

impl KimiCodeAdapter {
    fn base(&self, ctx: &Ctx) -> PathBuf {
        ctx.h(".kimi-code")
    }

    fn roots(&self, ctx: &Ctx) -> Vec<PathBuf> {
        let base = self.base(ctx);
        let mut v: Vec<PathBuf> = SUBTREES.iter().map(|r| base.join(r)).collect();
        v.extend(TOP_FILES.iter().map(|f| base.join(f)));
        v.into_iter().filter(|p| p.exists()).collect()
    }
}

impl Adapter for KimiCodeAdapter {
    fn name(&self) -> &'static str {
        "kimi"
    }
    fn display(&self) -> &'static str {
        "Kimi Code"
    }
    fn note(&self) -> &'static str {
        "~/.kimi-code workspaces.json + session_index.jsonl + sessions/, \
         file-history/ + workspace-trust/ + server/events keyed \
         wd_<basename>_<sha256(root)[:12]>; search-index (LMDB) skipped"
    }

    fn state_paths(&self, ctx: &Ctx) -> Vec<PathBuf> {
        vec![self.base(ctx)]
    }

    fn process_names(&self) -> &'static [&'static str] {
        // the CLI process is "kimi-code", the state-holding bridge
        // daemon "kimi-webbridge"; "kimi" covers the bare binary name
        &["kimi", "kimi-code", "kimi-webbridge"]
    }

    fn scan(&self, ctx: &Ctx, spec: &ReplaceSpec) -> Vec<Finding> {
        let base = self.base(ctx);
        let old_b = encodings::kimi_bucket(&spec.old);
        let new_b = encodings::kimi_bucket(&spec.new);
        let mut out =
            super::encoded_bucket_findings(self.name(), &base.join("sessions"), &old_b, &new_b);
        // the bucket also names FILES under file-history/ and
        // workspace-trust/
        for sub in ["file-history", "workspace-trust"] {
            let old_full = base.join(sub).join(&old_b);
            if old_full.is_file() {
                let detail = if new_b != old_b {
                    format!("-> {}", new_b)
                } else {
                    "bucket file".to_string()
                };
                out.push(mk(self.name(), "file_rename", &old_full, &detail));
            }
        }
        out.extend(self.scan_tree(spec, &self.roots(ctx)));
        out
    }

    fn migrate(
        &self,
        ctx: &Ctx,
        spec: &ReplaceSpec,
        backup: &mut Backup,
        deep: bool,
    ) -> Result<Vec<Finding>> {
        let base = self.base(ctx);
        let old_b = encodings::kimi_bucket(&spec.old);
        let new_b = encodings::kimi_bucket(&spec.new);
        let mut actions = Vec::new();
        if old_b != new_b {
            // sessions/<bucket> directories
            for (o, n) in
                super::rename_encoded_children(&base.join("sessions"), &old_b, &new_b, backup)
            {
                actions.push(mk(
                    self.name(),
                    "dir_rename",
                    &o,
                    &format!("-> {}", n.display()),
                ));
            }
            // file-history/ and workspace-trust/ hold FILES named by the
            // bucket (undo reverses renames for files and dirs alike)
            for sub in ["file-history", "workspace-trust"] {
                let parent = base.join(sub);
                let old_full = parent.join(&old_b);
                let new_full = parent.join(&new_b);
                if old_full.is_file() && !new_full.exists() {
                    backup.record_rename(&old_full, &new_full);
                    if std::fs::rename(&old_full, &new_full).is_ok() {
                        // bucket files are extensionless: the generic
                        // tree dispatch only rewrites known text
                        // extensions by default, so rewrite explicitly
                        // (workspace-trust holds {"root": ...}) — a
                        // failed rewrite on file-history (no paths) is
                        // harmless
                        let _ = rewriters::rewrite_text_file(&new_full, spec, backup);
                        actions.push(mk(
                            self.name(),
                            "file_rename",
                            &old_full,
                            &format!("-> {}", new_full.display()),
                        ));
                    }
                }
            }
        }
        actions.extend(self.migrate_text_tree(spec, backup, &self.roots(ctx), deep)?);
        // non-identity carriers the JSON cascade cannot see: the index
        // cache holds bare bucket ids in "ws" fields, and the server
        // event stream holds bucket ids under generic "id" /
        // "workspace_id" keys (their values are tokens, not paths).
        // Both are machine-replay state, so rewrite them as text and
        // let the boundary needles move every form. Failures are
        // non-fatal (the cache regenerates; events replay).
        let mut text_pass: Vec<PathBuf> = vec![base.join("sessions/.index-cache/scan.json")];
        let events = base.join("server/events");
        if let Ok(entries) = std::fs::read_dir(&events) {
            text_pass.extend(entries.filter_map(|e| e.ok()).map(|e| e.path()));
        }
        for p in text_pass {
            if p.is_file() {
                let _ = rewriters::rewrite_text_file(&p, spec, backup);
            }
        }
        // workspaces.json "name" is the creation-time basename — not a
        // path, so the generic rewrite leaves it behind while the KEY
        // moves to the new bucket; keep it consistent when it still
        // holds the old basename (a user-set display name is preserved)
        let old_base = encodings::basename(&spec.old);
        let new_base = encodings::basename(&spec.new);
        let ws_path = base.join("workspaces.json");
        if old_base != new_base && ws_path.is_file() {
            if let Ok(mut ws) =
                serde_json::from_str::<serde_json::Value>(&std::fs::read_to_string(&ws_path)?)
            {
                let mut changed = false;
                if let Some(map) = ws.get_mut("workspaces").and_then(|v| v.as_object_mut()) {
                    for (_k, w) in map.iter_mut() {
                        if w.get("name").and_then(|n| n.as_str()) == Some(old_base.as_str()) {
                            if let Some(obj) = w.as_object_mut() {
                                obj.insert(
                                    "name".to_string(),
                                    serde_json::Value::String(new_base.clone()),
                                );
                                changed = true;
                            }
                        }
                    }
                }
                if changed {
                    backup.record_file(&ws_path)?;
                    rewriters::write_atomic(
                        &ws_path,
                        serde_json::to_string_pretty(&ws)?.as_bytes(),
                    )?;
                }
            }
        }
        // the server event stream replays event.workspace.updated with
        // the same display name — it must follow the move too or a
        // replaying server revives the old workspace NAME under the new
        // id (observed on a live machine)
        if old_base != new_base {
            let evt_path = base.join("server/events/__global__.jsonl");
            if evt_path.is_file() {
                if let Ok(text) = std::fs::read_to_string(&evt_path) {
                    let mut out = String::with_capacity(text.len());
                    let mut changed = false;
                    for line in text.split_inclusive('\n') {
                        let mut handled = false;
                        if let Ok(mut o) = serde_json::from_str::<serde_json::Value>(
                            line.trim_end_matches(['\n', '\r']),
                        ) {
                            if let Some(ws) = o
                                .get_mut("envelope")
                                .and_then(|e| e.get_mut("payload"))
                                .and_then(|p| p.get_mut("workspace"))
                                .and_then(|w| w.as_object_mut())
                            {
                                if ws.get("name").and_then(|n| n.as_str())
                                    == Some(old_base.as_str())
                                {
                                    ws.insert(
                                        "name".to_string(),
                                        serde_json::Value::String(new_base.clone()),
                                    );
                                    changed = true;
                                    out.push_str(&serde_json::to_string(&o)?);
                                    if let Some(rest) =
                                        line.strip_prefix(line.trim_end_matches(['\n', '\r']))
                                    {
                                        out.push_str(rest);
                                    }
                                    handled = true;
                                }
                            }
                        }
                        if !handled {
                            out.push_str(line);
                        }
                    }
                    if changed {
                        backup.record_file(&evt_path)?;
                        rewriters::write_atomic(&evt_path, out.as_bytes())?;
                    }
                }
            }
        }
        // derived stores hold PRE-migration metadata: the server serves
        // session/workspace queries from cache/query-store and, until
        // invalidated, never re-reads the authoritative files (observed
        // live — a clean session_index/events/state still listed the
        // session under the old workspace). All three are caches by the
        // agent's own design and rebuild on next launch: remove them
        // (never during a dry run). Literal subpaths of the kimi base;
        // remove_dir_all does not follow symlinks.
        if !backup.dry_run {
            for derived in [
                base.join("cache/query-store"),
                base.join("sessions/.index-cache"),
                base.join("search-index"),
            ] {
                if derived.exists() {
                    let _ = std::fs::remove_dir_all(&derived);
                }
            }
        }
        Ok(actions)
    }
}
